BEGIN
	DBMS_OUTPUT.PUT('HELLO WORLD!');
	DBMS_OUTPUT.PUT_LINE('HOW ARE YOU?');
END;

BEGIN
	DBMS_OUTPUT.PUT('A ');
	DBMS_OUTPUT.PUT_LINE('B');
	DBMS_OUTPUT.PUT('C ');
	DBMS_OUTPUT.PUT('D');
	DBMS_OUTPUT.PUT_LINE(' ');
END;

DECLARE
	X NUMBER := 10;
	Y VARCHAR(20) := 'tops';
	Z FLOAT := 56.23;
BEGIN
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF Y = '||Y);
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF Z = '||Z);
END;

DECLARE -- FIRST BLOCK
	X NUMBER := 10;
BEGIN
	DECLARE -- SECOND BLOCK
		Y NUMBER := 20;
	BEGIN
		DECLARE -- THIRD BLOCK
			Z NUMBER := 30;
		BEGIN
			DBMS_OUTPUT.PUT_LINE('THIRD BLOCK :');
			DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
			DBMS_OUTPUT.PUT_LINE('THE VALUE OF Y = '||Y);
			DBMS_OUTPUT.PUT_LINE('THE VALUE OF Z = '||Z);
		END; -- THIRD BLOCK
		DBMS_OUTPUT.PUT_LINE('SECOND BLOCK :');
		DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
		DBMS_OUTPUT.PUT_LINE('THE VALUE OF Y = '||Y);
	END; -- SECOND BLOCK
	DBMS_OUTPUT.PUT_LINE('FIRST BLOCK :');
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
END; -- FIRST BLOCK

-- CONDITIONAL STATEMENTS
DECLARE
	NUM NUMBER := 1;
BEGIN
	IF MOD(NUM,2)=0 THEN
		DBMS_OUTPUT.PUT_LINE(NUM||' IS AN EVEN NUMBER');
	ELSE
		DBMS_OUTPUT.PUT_LINE(NUM||' IS AN ODD NUMBER');
	END IF;
END;

DECLARE
	N1 NUMBER := 45;
	N2 NUMBER := 105;
	N3 NUMBER := 85;
BEGIN
	IF N1>N2 AND N1>N3 THEN
		DBMS_OUTPUT.PUT_LINE(N1||' IS THE BIGGEST NUMBER');
	ELSIF N2>N1 AND N2>N3 THEN
		DBMS_OUTPUT.PUT_LINE(N2||' IS THE BIGGEST NUMBER');
	ELSE
		DBMS_OUTPUT.PUT_LINE(N3||' IS THE BIGGEST NUMBER');
	END IF;
END;

DECLARE
	N1 NUMBER := 45;
	N2 NUMBER := 95;
	N3 NUMBER := 85;
BEGIN
	IF N1>N2 THEN
		IF N1>N3 THEN
			DBMS_OUTPUT.PUT_LINE(N1||' IS THE BIGGEST NUMBER');
		ELSE
			DBMS_OUTPUT.PUT_LINE(N3||' IS THE BIGGEST NUMBER');
		END IF;
	ELSE
		IF N2>N3 THEN
			DBMS_OUTPUT.PUT_LINE(N2||' IS THE BIGGEST NUMBER');
		ELSE
			DBMS_OUTPUT.PUT_LINE(N3||' IS THE BIGGEST NUMBER');
		END IF;
	END IF;
END;

-- SIMPLE LOOP
DECLARE
	I NUMBER := 1;
BEGIN
	LOOP
		DBMS_OUTPUT.PUT_LINE('TOPS TECHNOLOGIES'); --4
		IF I=5 THEN
            EXIT;
		END IF;
		I := I + 1;
	END LOOP;
END;

-- SIMPLE LOOP
DECLARE
	I NUMBER := 1;
BEGIN
	LOOP
		DBMS_OUTPUT.PUT_LINE('TOPS TECHNOLOGIES'); --4
		EXIT WHEN I=5;
		I := I + 1;
	END LOOP;
END;

-- FOR LOOP
BEGIN
	FOR X IN 1..5 LOOP
		DBMS_OUTPUT.PUT_LINE(X||'. TOPS TECHNOLOGIES');
	END LOOP;
END;

-- FOR LOOP
DECLARE
	X NUMBER := 101;
BEGIN
	FOR Y IN 1..5 LOOP
		DBMS_OUTPUT.PUT_LINE(X||'. TOPS TECHNOLOGIES');
		X := X+1;
	END LOOP;
END;

-- WHILE LOOP
DECLARE 
	I NUMBER := 1;
BEGIN
	WHILE I<=5 LOOP
		DBMS_OUTPUT.PUT_LINE('TOPS TECHNOLOGIES');
		I := I+1;
	END LOOP;
END;

DECLARE
	NUM NUMBER := 70;
	CNT NUMBER := 0;
BEGIN
	FOR I IN 2..NUM/2 LOOP
		IF MOD(NUM,I)=0 THEN
			CNT := 1;
			EXIT;
		END IF;
	END LOOP;
	IF CNT=0 THEN
		DBMS_OUTPUT.PUT_LINE(NUM||' IS A PRIME NUMBER');
	ELSE
		DBMS_OUTPUT.PUT_LINE(NUM||' IS NOT A PRIME NUMBER');
	END IF;
END;

DECLARE
	ROW NUMBER := 5;
	SPC NUMBER := ROW-1;
BEGIN
	FOR I IN 1..ROW LOOP
		FOR J IN 1..SPC LOOP
			DBMS_OUTPUT.PUT(' ');
		END LOOP;
		FOR K IN 1..I LOOP
			DBMS_OUTPUT.PUT('* ');
		END LOOP;
		DBMS_OUTPUT.PUT_LINE('');
		SPC := SPC - 1;
	END LOOP;
END;

--EXPLICIT CURSOR
DECLARE
FNAME EMPLOYEES.FIRST_NAME%TYPE;
LNAME EMPLOYEES.LAST_NAME%TYPE;
SAL EMPLOYEES.SALARY%TYPE;
DID EMPLOYEES.DEPARTMENT_ID%TYPE;
MID EMPLOYEES.MANAGER_ID%TYPE;
CURSOR EMP_DETAIL IS SELECT FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_ID,MANAGER_ID FROM EMPLOYEES;
BEGIN
    OPEN EMP_DETAIL;
	LOOP
		FETCH EMP_DETAIL INTO FNAME,LNAME,SAL,DID,MID;
		DBMS_OUTPUT.PUT_LINE(FNAME||' '||LNAME||"'S MONTHLY SALARY IS "||SAL||' WHO WORKS IN DEPARTMENT '||DID||' UNDER MANAGER '||MID);
		IF EMP_DETAIL%NOTFOUND THEN
			EXIT;
		END IF;
	END LOOP;
	CLOSE EMP_DETAIL;
END;

--IMPLICIT CURSOR
DECLARE
	ROW_NUMBER NUMBER := 0;
BEGIN
	UPDATE EMPLOYEES SET SALARY = SALARY + 10000 WHERE DEPARTMENT_ID = 500;
	IF SQL%FOUND THEN
		ROW_NUMBER := SQL%ROWCOUNT;
	ELSE
		DBMS_OUTPUT.PUT_LINE('NO DATA IS UPDATED');
	END IF;
	DBMS_OUTPUT.PUT_LINE('UPDATED ROWS = '||ROW_NUMBER);
END;