BEGIN
	DBMS_OUTPUT.PUT('HELLO WORLD!');
	DBMS_OUTPUT.PUT_LINE('HOW ARE YOU?');
END;

BEGIN
	DBMS_OUTPUT.PUT('A ');
	DBMS_OUTPUT.PUT_LINE('B');
	DBMS_OUTPUT.PUT('C ');
	DBMS_OUTPUT.PUT('D');
	DBMS_OUTPUT.PUT_LINE(' ');
END;

DECLARE
	X NUMBER := 10;
	Y VARCHAR(20) := 'tops';
	Z FLOAT := 56.23;
BEGIN
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF Y = '||Y);
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF Z = '||Z);
END;

DECLARE -- FIRST BLOCK
	X NUMBER := 10;
BEGIN
	DECLARE -- SECOND BLOCK
		Y NUMBER := 20;
	BEGIN
		DECLARE -- THIRD BLOCK
			Z NUMBER := 30;
		BEGIN
			DBMS_OUTPUT.PUT_LINE('THIRD BLOCK :');
			DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
			DBMS_OUTPUT.PUT_LINE('THE VALUE OF Y = '||Y);
			DBMS_OUTPUT.PUT_LINE('THE VALUE OF Z = '||Z);
		END; -- THIRD BLOCK
		DBMS_OUTPUT.PUT_LINE('SECOND BLOCK :');
		DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
		DBMS_OUTPUT.PUT_LINE('THE VALUE OF Y = '||Y);
	END; -- SECOND BLOCK
	DBMS_OUTPUT.PUT_LINE('FIRST BLOCK :');
	DBMS_OUTPUT.PUT_LINE('THE VALUE OF X = '||X);
END; -- FIRST BLOCK